name: Prison
version: '1.0-SNAPSHOT'
main: ksu.minecraft.prison.Prison
api-version: '1.21'
description: A prison plugin for Minecraft

commands:
  prison:
    description: Main command for the Prison plugin
    usage: /prison <args>
    aliases: [prison]
  ranks:
    description: Shows rank progression and costs
    usage: /ranks
  rankup:
    description: Ranks up the player if they can afford it
    usage: /rankup
  cells:
    description: View and rent cells
    usage: /cells
  mine:
    description: Admin-only command to access the mines
    usage: /mine
    permission: prison.admin
    permission-message: You do not have permission to use this command.
#  minereset:
#    description: Resets the specified mine
#    usage: /minereset <minename>
#    permission: prison.admin
#    permission-message: You do not have permission to use this command.
softdepend: [LuckPerms]

permissions:
  prison.use:
    description: Allows a player to use the /prison command.
    default: true
  prison.admin:
    description: Allows a player to use admin commands for the plugin.
    default: op
permission-message: You do not have permission to execute this command.
